// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ondewo/survey/fhir.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ondewo_2fsurvey_2ffhir_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ondewo_2fsurvey_2ffhir_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "google/api/annotations.pb.h"
#include "ondewo/survey/survey.pb.h"
#include <google/protobuf/struct.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ondewo_2fsurvey_2ffhir_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ondewo_2fsurvey_2ffhir_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ondewo_2fsurvey_2ffhir_2eproto;
namespace ondewo {
namespace survey {
class CreateFHIRSurveyRequest;
struct CreateFHIRSurveyRequestDefaultTypeInternal;
extern CreateFHIRSurveyRequestDefaultTypeInternal _CreateFHIRSurveyRequest_default_instance_;
class SurveyFHIRAnswersResponse;
struct SurveyFHIRAnswersResponseDefaultTypeInternal;
extern SurveyFHIRAnswersResponseDefaultTypeInternal _SurveyFHIRAnswersResponse_default_instance_;
}  // namespace survey
}  // namespace ondewo
PROTOBUF_NAMESPACE_OPEN
template<> ::ondewo::survey::CreateFHIRSurveyRequest* Arena::CreateMaybeMessage<::ondewo::survey::CreateFHIRSurveyRequest>(Arena*);
template<> ::ondewo::survey::SurveyFHIRAnswersResponse* Arena::CreateMaybeMessage<::ondewo::survey::SurveyFHIRAnswersResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ondewo {
namespace survey {

// ===================================================================

class CreateFHIRSurveyRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ondewo.survey.CreateFHIRSurveyRequest) */ {
 public:
  inline CreateFHIRSurveyRequest() : CreateFHIRSurveyRequest(nullptr) {}
  ~CreateFHIRSurveyRequest() override;
  explicit PROTOBUF_CONSTEXPR CreateFHIRSurveyRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CreateFHIRSurveyRequest(const CreateFHIRSurveyRequest& from);
  CreateFHIRSurveyRequest(CreateFHIRSurveyRequest&& from) noexcept
    : CreateFHIRSurveyRequest() {
    *this = ::std::move(from);
  }

  inline CreateFHIRSurveyRequest& operator=(const CreateFHIRSurveyRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateFHIRSurveyRequest& operator=(CreateFHIRSurveyRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CreateFHIRSurveyRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const CreateFHIRSurveyRequest* internal_default_instance() {
    return reinterpret_cast<const CreateFHIRSurveyRequest*>(
               &_CreateFHIRSurveyRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CreateFHIRSurveyRequest& a, CreateFHIRSurveyRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CreateFHIRSurveyRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateFHIRSurveyRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CreateFHIRSurveyRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CreateFHIRSurveyRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CreateFHIRSurveyRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CreateFHIRSurveyRequest& from) {
    CreateFHIRSurveyRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateFHIRSurveyRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ondewo.survey.CreateFHIRSurveyRequest";
  }
  protected:
  explicit CreateFHIRSurveyRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFhirQuestionnaireFieldNumber = 1,
  };
  // .google.protobuf.Struct fhir_questionnaire = 1;
  bool has_fhir_questionnaire() const;
  private:
  bool _internal_has_fhir_questionnaire() const;
  public:
  void clear_fhir_questionnaire();
  const ::PROTOBUF_NAMESPACE_ID::Struct& fhir_questionnaire() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Struct* release_fhir_questionnaire();
  ::PROTOBUF_NAMESPACE_ID::Struct* mutable_fhir_questionnaire();
  void set_allocated_fhir_questionnaire(::PROTOBUF_NAMESPACE_ID::Struct* fhir_questionnaire);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Struct& _internal_fhir_questionnaire() const;
  ::PROTOBUF_NAMESPACE_ID::Struct* _internal_mutable_fhir_questionnaire();
  public:
  void unsafe_arena_set_allocated_fhir_questionnaire(
      ::PROTOBUF_NAMESPACE_ID::Struct* fhir_questionnaire);
  ::PROTOBUF_NAMESPACE_ID::Struct* unsafe_arena_release_fhir_questionnaire();

  // @@protoc_insertion_point(class_scope:ondewo.survey.CreateFHIRSurveyRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::Struct* fhir_questionnaire_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ondewo_2fsurvey_2ffhir_2eproto;
};
// -------------------------------------------------------------------

class SurveyFHIRAnswersResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ondewo.survey.SurveyFHIRAnswersResponse) */ {
 public:
  inline SurveyFHIRAnswersResponse() : SurveyFHIRAnswersResponse(nullptr) {}
  ~SurveyFHIRAnswersResponse() override;
  explicit PROTOBUF_CONSTEXPR SurveyFHIRAnswersResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SurveyFHIRAnswersResponse(const SurveyFHIRAnswersResponse& from);
  SurveyFHIRAnswersResponse(SurveyFHIRAnswersResponse&& from) noexcept
    : SurveyFHIRAnswersResponse() {
    *this = ::std::move(from);
  }

  inline SurveyFHIRAnswersResponse& operator=(const SurveyFHIRAnswersResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SurveyFHIRAnswersResponse& operator=(SurveyFHIRAnswersResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SurveyFHIRAnswersResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SurveyFHIRAnswersResponse* internal_default_instance() {
    return reinterpret_cast<const SurveyFHIRAnswersResponse*>(
               &_SurveyFHIRAnswersResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SurveyFHIRAnswersResponse& a, SurveyFHIRAnswersResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SurveyFHIRAnswersResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SurveyFHIRAnswersResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SurveyFHIRAnswersResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SurveyFHIRAnswersResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SurveyFHIRAnswersResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SurveyFHIRAnswersResponse& from) {
    SurveyFHIRAnswersResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SurveyFHIRAnswersResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ondewo.survey.SurveyFHIRAnswersResponse";
  }
  protected:
  explicit SurveyFHIRAnswersResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFhirQuestionnaireResponsesFieldNumber = 2,
    kSurveyIdFieldNumber = 1,
  };
  // repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;
  int fhir_questionnaire_responses_size() const;
  private:
  int _internal_fhir_questionnaire_responses_size() const;
  public:
  void clear_fhir_questionnaire_responses();
  ::PROTOBUF_NAMESPACE_ID::Struct* mutable_fhir_questionnaire_responses(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PROTOBUF_NAMESPACE_ID::Struct >*
      mutable_fhir_questionnaire_responses();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Struct& _internal_fhir_questionnaire_responses(int index) const;
  ::PROTOBUF_NAMESPACE_ID::Struct* _internal_add_fhir_questionnaire_responses();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Struct& fhir_questionnaire_responses(int index) const;
  ::PROTOBUF_NAMESPACE_ID::Struct* add_fhir_questionnaire_responses();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PROTOBUF_NAMESPACE_ID::Struct >&
      fhir_questionnaire_responses() const;

  // string survey_id = 1;
  void clear_survey_id();
  const std::string& survey_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_survey_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_survey_id();
  PROTOBUF_NODISCARD std::string* release_survey_id();
  void set_allocated_survey_id(std::string* survey_id);
  private:
  const std::string& _internal_survey_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_survey_id(const std::string& value);
  std::string* _internal_mutable_survey_id();
  public:

  // @@protoc_insertion_point(class_scope:ondewo.survey.SurveyFHIRAnswersResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PROTOBUF_NAMESPACE_ID::Struct > fhir_questionnaire_responses_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr survey_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ondewo_2fsurvey_2ffhir_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CreateFHIRSurveyRequest

// .google.protobuf.Struct fhir_questionnaire = 1;
inline bool CreateFHIRSurveyRequest::_internal_has_fhir_questionnaire() const {
  return this != internal_default_instance() && _impl_.fhir_questionnaire_ != nullptr;
}
inline bool CreateFHIRSurveyRequest::has_fhir_questionnaire() const {
  return _internal_has_fhir_questionnaire();
}
inline const ::PROTOBUF_NAMESPACE_ID::Struct& CreateFHIRSurveyRequest::_internal_fhir_questionnaire() const {
  const ::PROTOBUF_NAMESPACE_ID::Struct* p = _impl_.fhir_questionnaire_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Struct&>(
      ::PROTOBUF_NAMESPACE_ID::_Struct_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Struct& CreateFHIRSurveyRequest::fhir_questionnaire() const {
  // @@protoc_insertion_point(field_get:ondewo.survey.CreateFHIRSurveyRequest.fhir_questionnaire)
  return _internal_fhir_questionnaire();
}
inline void CreateFHIRSurveyRequest::unsafe_arena_set_allocated_fhir_questionnaire(
    ::PROTOBUF_NAMESPACE_ID::Struct* fhir_questionnaire) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.fhir_questionnaire_);
  }
  _impl_.fhir_questionnaire_ = fhir_questionnaire;
  if (fhir_questionnaire) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ondewo.survey.CreateFHIRSurveyRequest.fhir_questionnaire)
}
inline ::PROTOBUF_NAMESPACE_ID::Struct* CreateFHIRSurveyRequest::release_fhir_questionnaire() {
  
  ::PROTOBUF_NAMESPACE_ID::Struct* temp = _impl_.fhir_questionnaire_;
  _impl_.fhir_questionnaire_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Struct* CreateFHIRSurveyRequest::unsafe_arena_release_fhir_questionnaire() {
  // @@protoc_insertion_point(field_release:ondewo.survey.CreateFHIRSurveyRequest.fhir_questionnaire)
  
  ::PROTOBUF_NAMESPACE_ID::Struct* temp = _impl_.fhir_questionnaire_;
  _impl_.fhir_questionnaire_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Struct* CreateFHIRSurveyRequest::_internal_mutable_fhir_questionnaire() {
  
  if (_impl_.fhir_questionnaire_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Struct>(GetArenaForAllocation());
    _impl_.fhir_questionnaire_ = p;
  }
  return _impl_.fhir_questionnaire_;
}
inline ::PROTOBUF_NAMESPACE_ID::Struct* CreateFHIRSurveyRequest::mutable_fhir_questionnaire() {
  ::PROTOBUF_NAMESPACE_ID::Struct* _msg = _internal_mutable_fhir_questionnaire();
  // @@protoc_insertion_point(field_mutable:ondewo.survey.CreateFHIRSurveyRequest.fhir_questionnaire)
  return _msg;
}
inline void CreateFHIRSurveyRequest::set_allocated_fhir_questionnaire(::PROTOBUF_NAMESPACE_ID::Struct* fhir_questionnaire) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.fhir_questionnaire_);
  }
  if (fhir_questionnaire) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(fhir_questionnaire));
    if (message_arena != submessage_arena) {
      fhir_questionnaire = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, fhir_questionnaire, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.fhir_questionnaire_ = fhir_questionnaire;
  // @@protoc_insertion_point(field_set_allocated:ondewo.survey.CreateFHIRSurveyRequest.fhir_questionnaire)
}

// -------------------------------------------------------------------

// SurveyFHIRAnswersResponse

// string survey_id = 1;
inline void SurveyFHIRAnswersResponse::clear_survey_id() {
  _impl_.survey_id_.ClearToEmpty();
}
inline const std::string& SurveyFHIRAnswersResponse::survey_id() const {
  // @@protoc_insertion_point(field_get:ondewo.survey.SurveyFHIRAnswersResponse.survey_id)
  return _internal_survey_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SurveyFHIRAnswersResponse::set_survey_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.survey_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ondewo.survey.SurveyFHIRAnswersResponse.survey_id)
}
inline std::string* SurveyFHIRAnswersResponse::mutable_survey_id() {
  std::string* _s = _internal_mutable_survey_id();
  // @@protoc_insertion_point(field_mutable:ondewo.survey.SurveyFHIRAnswersResponse.survey_id)
  return _s;
}
inline const std::string& SurveyFHIRAnswersResponse::_internal_survey_id() const {
  return _impl_.survey_id_.Get();
}
inline void SurveyFHIRAnswersResponse::_internal_set_survey_id(const std::string& value) {
  
  _impl_.survey_id_.Set(value, GetArenaForAllocation());
}
inline std::string* SurveyFHIRAnswersResponse::_internal_mutable_survey_id() {
  
  return _impl_.survey_id_.Mutable(GetArenaForAllocation());
}
inline std::string* SurveyFHIRAnswersResponse::release_survey_id() {
  // @@protoc_insertion_point(field_release:ondewo.survey.SurveyFHIRAnswersResponse.survey_id)
  return _impl_.survey_id_.Release();
}
inline void SurveyFHIRAnswersResponse::set_allocated_survey_id(std::string* survey_id) {
  if (survey_id != nullptr) {
    
  } else {
    
  }
  _impl_.survey_id_.SetAllocated(survey_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.survey_id_.IsDefault()) {
    _impl_.survey_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ondewo.survey.SurveyFHIRAnswersResponse.survey_id)
}

// repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;
inline int SurveyFHIRAnswersResponse::_internal_fhir_questionnaire_responses_size() const {
  return _impl_.fhir_questionnaire_responses_.size();
}
inline int SurveyFHIRAnswersResponse::fhir_questionnaire_responses_size() const {
  return _internal_fhir_questionnaire_responses_size();
}
inline ::PROTOBUF_NAMESPACE_ID::Struct* SurveyFHIRAnswersResponse::mutable_fhir_questionnaire_responses(int index) {
  // @@protoc_insertion_point(field_mutable:ondewo.survey.SurveyFHIRAnswersResponse.fhir_questionnaire_responses)
  return _impl_.fhir_questionnaire_responses_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PROTOBUF_NAMESPACE_ID::Struct >*
SurveyFHIRAnswersResponse::mutable_fhir_questionnaire_responses() {
  // @@protoc_insertion_point(field_mutable_list:ondewo.survey.SurveyFHIRAnswersResponse.fhir_questionnaire_responses)
  return &_impl_.fhir_questionnaire_responses_;
}
inline const ::PROTOBUF_NAMESPACE_ID::Struct& SurveyFHIRAnswersResponse::_internal_fhir_questionnaire_responses(int index) const {
  return _impl_.fhir_questionnaire_responses_.Get(index);
}
inline const ::PROTOBUF_NAMESPACE_ID::Struct& SurveyFHIRAnswersResponse::fhir_questionnaire_responses(int index) const {
  // @@protoc_insertion_point(field_get:ondewo.survey.SurveyFHIRAnswersResponse.fhir_questionnaire_responses)
  return _internal_fhir_questionnaire_responses(index);
}
inline ::PROTOBUF_NAMESPACE_ID::Struct* SurveyFHIRAnswersResponse::_internal_add_fhir_questionnaire_responses() {
  return _impl_.fhir_questionnaire_responses_.Add();
}
inline ::PROTOBUF_NAMESPACE_ID::Struct* SurveyFHIRAnswersResponse::add_fhir_questionnaire_responses() {
  ::PROTOBUF_NAMESPACE_ID::Struct* _add = _internal_add_fhir_questionnaire_responses();
  // @@protoc_insertion_point(field_add:ondewo.survey.SurveyFHIRAnswersResponse.fhir_questionnaire_responses)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PROTOBUF_NAMESPACE_ID::Struct >&
SurveyFHIRAnswersResponse::fhir_questionnaire_responses() const {
  // @@protoc_insertion_point(field_list:ondewo.survey.SurveyFHIRAnswersResponse.fhir_questionnaire_responses)
  return _impl_.fhir_questionnaire_responses_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace survey
}  // namespace ondewo

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ondewo_2fsurvey_2ffhir_2eproto
