// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ondewo/survey/fhir.proto
// Original file comments:
// Copyright 2020 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License. (editesyntax = "proto3";
#ifndef GRPC_ondewo_2fsurvey_2ffhir_2eproto__INCLUDED
#define GRPC_ondewo_2fsurvey_2ffhir_2eproto__INCLUDED

#include "ondewo/survey/fhir.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ondewo {
namespace survey {

// ///// FHIR Services ///////
//
// The following servicer was designed to support the FHIR standard.
// Both Questionnaires and Responses will be detected and transformed for a simpler usage.
//
class FHIR final {
 public:
  static constexpr char const* service_full_name() {
    return "ondewo.survey.FHIR";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Create a Survey from FHIR format and an empty NLU Agent for it
    virtual ::grpc::Status CreateFHIRSurvey(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest& request, ::ondewo::survey::Survey* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::Survey>> AsyncCreateFHIRSurvey(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::Survey>>(AsyncCreateFHIRSurveyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::Survey>> PrepareAsyncCreateFHIRSurvey(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::Survey>>(PrepareAsyncCreateFHIRSurveyRaw(context, request, cq));
    }
    // Get Survey Answers on FHIR format
    virtual ::grpc::Status GetFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest& request, ::ondewo::survey::SurveyFHIRAnswersResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::SurveyFHIRAnswersResponse>> AsyncGetFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::SurveyFHIRAnswersResponse>>(AsyncGetFHIRSurveyAnswersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::SurveyFHIRAnswersResponse>> PrepareAsyncGetFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::SurveyFHIRAnswersResponse>>(PrepareAsyncGetFHIRSurveyAnswersRaw(context, request, cq));
    }
    // Get all Survey Answers on FHIR format
    virtual ::grpc::Status GetAllFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest& request, ::ondewo::survey::SurveyFHIRAnswersResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::SurveyFHIRAnswersResponse>> AsyncGetAllFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::SurveyFHIRAnswersResponse>>(AsyncGetAllFHIRSurveyAnswersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::SurveyFHIRAnswersResponse>> PrepareAsyncGetAllFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::SurveyFHIRAnswersResponse>>(PrepareAsyncGetAllFHIRSurveyAnswersRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Create a Survey from FHIR format and an empty NLU Agent for it
      virtual void CreateFHIRSurvey(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest* request, ::ondewo::survey::Survey* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateFHIRSurvey(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest* request, ::ondewo::survey::Survey* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Get Survey Answers on FHIR format
      virtual void GetFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Get all Survey Answers on FHIR format
      virtual void GetAllFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetAllFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::Survey>* AsyncCreateFHIRSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::Survey>* PrepareAsyncCreateFHIRSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::SurveyFHIRAnswersResponse>* AsyncGetFHIRSurveyAnswersRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::SurveyFHIRAnswersResponse>* PrepareAsyncGetFHIRSurveyAnswersRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::SurveyFHIRAnswersResponse>* AsyncGetAllFHIRSurveyAnswersRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::survey::SurveyFHIRAnswersResponse>* PrepareAsyncGetAllFHIRSurveyAnswersRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CreateFHIRSurvey(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest& request, ::ondewo::survey::Survey* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::survey::Survey>> AsyncCreateFHIRSurvey(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::survey::Survey>>(AsyncCreateFHIRSurveyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::survey::Survey>> PrepareAsyncCreateFHIRSurvey(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::survey::Survey>>(PrepareAsyncCreateFHIRSurveyRaw(context, request, cq));
    }
    ::grpc::Status GetFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest& request, ::ondewo::survey::SurveyFHIRAnswersResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyFHIRAnswersResponse>> AsyncGetFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyFHIRAnswersResponse>>(AsyncGetFHIRSurveyAnswersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyFHIRAnswersResponse>> PrepareAsyncGetFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyFHIRAnswersResponse>>(PrepareAsyncGetFHIRSurveyAnswersRaw(context, request, cq));
    }
    ::grpc::Status GetAllFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest& request, ::ondewo::survey::SurveyFHIRAnswersResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyFHIRAnswersResponse>> AsyncGetAllFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyFHIRAnswersResponse>>(AsyncGetAllFHIRSurveyAnswersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyFHIRAnswersResponse>> PrepareAsyncGetAllFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyFHIRAnswersResponse>>(PrepareAsyncGetAllFHIRSurveyAnswersRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CreateFHIRSurvey(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest* request, ::ondewo::survey::Survey* response, std::function<void(::grpc::Status)>) override;
      void CreateFHIRSurvey(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest* request, ::ondewo::survey::Survey* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response, std::function<void(::grpc::Status)>) override;
      void GetFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetAllFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response, std::function<void(::grpc::Status)>) override;
      void GetAllFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ondewo::survey::Survey>* AsyncCreateFHIRSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::survey::Survey>* PrepareAsyncCreateFHIRSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyFHIRAnswersResponse>* AsyncGetFHIRSurveyAnswersRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyFHIRAnswersResponse>* PrepareAsyncGetFHIRSurveyAnswersRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyFHIRAnswersResponse>* AsyncGetAllFHIRSurveyAnswersRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyFHIRAnswersResponse>* PrepareAsyncGetAllFHIRSurveyAnswersRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CreateFHIRSurvey_;
    const ::grpc::internal::RpcMethod rpcmethod_GetFHIRSurveyAnswers_;
    const ::grpc::internal::RpcMethod rpcmethod_GetAllFHIRSurveyAnswers_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Create a Survey from FHIR format and an empty NLU Agent for it
    virtual ::grpc::Status CreateFHIRSurvey(::grpc::ServerContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest* request, ::ondewo::survey::Survey* response);
    // Get Survey Answers on FHIR format
    virtual ::grpc::Status GetFHIRSurveyAnswers(::grpc::ServerContext* context, const ::ondewo::survey::GetSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response);
    // Get all Survey Answers on FHIR format
    virtual ::grpc::Status GetAllFHIRSurveyAnswers(::grpc::ServerContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateFHIRSurvey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateFHIRSurvey() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CreateFHIRSurvey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFHIRSurvey(::grpc::ServerContext* /*context*/, const ::ondewo::survey::CreateFHIRSurveyRequest* /*request*/, ::ondewo::survey::Survey* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateFHIRSurvey(::grpc::ServerContext* context, ::ondewo::survey::CreateFHIRSurveyRequest* request, ::grpc::ServerAsyncResponseWriter< ::ondewo::survey::Survey>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetFHIRSurveyAnswers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetFHIRSurveyAnswers() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetFHIRSurveyAnswers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFHIRSurveyAnswers(::grpc::ServerContext* /*context*/, const ::ondewo::survey::GetSurveyAnswersRequest* /*request*/, ::ondewo::survey::SurveyFHIRAnswersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFHIRSurveyAnswers(::grpc::ServerContext* context, ::ondewo::survey::GetSurveyAnswersRequest* request, ::grpc::ServerAsyncResponseWriter< ::ondewo::survey::SurveyFHIRAnswersResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetAllFHIRSurveyAnswers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetAllFHIRSurveyAnswers() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetAllFHIRSurveyAnswers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAllFHIRSurveyAnswers(::grpc::ServerContext* /*context*/, const ::ondewo::survey::GetAllSurveyAnswersRequest* /*request*/, ::ondewo::survey::SurveyFHIRAnswersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAllFHIRSurveyAnswers(::grpc::ServerContext* context, ::ondewo::survey::GetAllSurveyAnswersRequest* request, ::grpc::ServerAsyncResponseWriter< ::ondewo::survey::SurveyFHIRAnswersResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CreateFHIRSurvey<WithAsyncMethod_GetFHIRSurveyAnswers<WithAsyncMethod_GetAllFHIRSurveyAnswers<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CreateFHIRSurvey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateFHIRSurvey() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ondewo::survey::CreateFHIRSurveyRequest, ::ondewo::survey::Survey>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest* request, ::ondewo::survey::Survey* response) { return this->CreateFHIRSurvey(context, request, response); }));}
    void SetMessageAllocatorFor_CreateFHIRSurvey(
        ::grpc::MessageAllocator< ::ondewo::survey::CreateFHIRSurveyRequest, ::ondewo::survey::Survey>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ondewo::survey::CreateFHIRSurveyRequest, ::ondewo::survey::Survey>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateFHIRSurvey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFHIRSurvey(::grpc::ServerContext* /*context*/, const ::ondewo::survey::CreateFHIRSurveyRequest* /*request*/, ::ondewo::survey::Survey* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateFHIRSurvey(
      ::grpc::CallbackServerContext* /*context*/, const ::ondewo::survey::CreateFHIRSurveyRequest* /*request*/, ::ondewo::survey::Survey* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetFHIRSurveyAnswers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetFHIRSurveyAnswers() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::ondewo::survey::GetSurveyAnswersRequest, ::ondewo::survey::SurveyFHIRAnswersResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ondewo::survey::GetSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response) { return this->GetFHIRSurveyAnswers(context, request, response); }));}
    void SetMessageAllocatorFor_GetFHIRSurveyAnswers(
        ::grpc::MessageAllocator< ::ondewo::survey::GetSurveyAnswersRequest, ::ondewo::survey::SurveyFHIRAnswersResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ondewo::survey::GetSurveyAnswersRequest, ::ondewo::survey::SurveyFHIRAnswersResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetFHIRSurveyAnswers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFHIRSurveyAnswers(::grpc::ServerContext* /*context*/, const ::ondewo::survey::GetSurveyAnswersRequest* /*request*/, ::ondewo::survey::SurveyFHIRAnswersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetFHIRSurveyAnswers(
      ::grpc::CallbackServerContext* /*context*/, const ::ondewo::survey::GetSurveyAnswersRequest* /*request*/, ::ondewo::survey::SurveyFHIRAnswersResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetAllFHIRSurveyAnswers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetAllFHIRSurveyAnswers() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::ondewo::survey::GetAllSurveyAnswersRequest, ::ondewo::survey::SurveyFHIRAnswersResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response) { return this->GetAllFHIRSurveyAnswers(context, request, response); }));}
    void SetMessageAllocatorFor_GetAllFHIRSurveyAnswers(
        ::grpc::MessageAllocator< ::ondewo::survey::GetAllSurveyAnswersRequest, ::ondewo::survey::SurveyFHIRAnswersResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ondewo::survey::GetAllSurveyAnswersRequest, ::ondewo::survey::SurveyFHIRAnswersResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetAllFHIRSurveyAnswers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAllFHIRSurveyAnswers(::grpc::ServerContext* /*context*/, const ::ondewo::survey::GetAllSurveyAnswersRequest* /*request*/, ::ondewo::survey::SurveyFHIRAnswersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAllFHIRSurveyAnswers(
      ::grpc::CallbackServerContext* /*context*/, const ::ondewo::survey::GetAllSurveyAnswersRequest* /*request*/, ::ondewo::survey::SurveyFHIRAnswersResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CreateFHIRSurvey<WithCallbackMethod_GetFHIRSurveyAnswers<WithCallbackMethod_GetAllFHIRSurveyAnswers<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CreateFHIRSurvey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateFHIRSurvey() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CreateFHIRSurvey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFHIRSurvey(::grpc::ServerContext* /*context*/, const ::ondewo::survey::CreateFHIRSurveyRequest* /*request*/, ::ondewo::survey::Survey* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetFHIRSurveyAnswers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetFHIRSurveyAnswers() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetFHIRSurveyAnswers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFHIRSurveyAnswers(::grpc::ServerContext* /*context*/, const ::ondewo::survey::GetSurveyAnswersRequest* /*request*/, ::ondewo::survey::SurveyFHIRAnswersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetAllFHIRSurveyAnswers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetAllFHIRSurveyAnswers() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetAllFHIRSurveyAnswers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAllFHIRSurveyAnswers(::grpc::ServerContext* /*context*/, const ::ondewo::survey::GetAllSurveyAnswersRequest* /*request*/, ::ondewo::survey::SurveyFHIRAnswersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateFHIRSurvey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateFHIRSurvey() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CreateFHIRSurvey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFHIRSurvey(::grpc::ServerContext* /*context*/, const ::ondewo::survey::CreateFHIRSurveyRequest* /*request*/, ::ondewo::survey::Survey* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateFHIRSurvey(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetFHIRSurveyAnswers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetFHIRSurveyAnswers() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetFHIRSurveyAnswers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFHIRSurveyAnswers(::grpc::ServerContext* /*context*/, const ::ondewo::survey::GetSurveyAnswersRequest* /*request*/, ::ondewo::survey::SurveyFHIRAnswersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFHIRSurveyAnswers(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetAllFHIRSurveyAnswers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetAllFHIRSurveyAnswers() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetAllFHIRSurveyAnswers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAllFHIRSurveyAnswers(::grpc::ServerContext* /*context*/, const ::ondewo::survey::GetAllSurveyAnswersRequest* /*request*/, ::ondewo::survey::SurveyFHIRAnswersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAllFHIRSurveyAnswers(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateFHIRSurvey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateFHIRSurvey() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateFHIRSurvey(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateFHIRSurvey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFHIRSurvey(::grpc::ServerContext* /*context*/, const ::ondewo::survey::CreateFHIRSurveyRequest* /*request*/, ::ondewo::survey::Survey* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateFHIRSurvey(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetFHIRSurveyAnswers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetFHIRSurveyAnswers() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetFHIRSurveyAnswers(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetFHIRSurveyAnswers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFHIRSurveyAnswers(::grpc::ServerContext* /*context*/, const ::ondewo::survey::GetSurveyAnswersRequest* /*request*/, ::ondewo::survey::SurveyFHIRAnswersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetFHIRSurveyAnswers(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetAllFHIRSurveyAnswers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetAllFHIRSurveyAnswers() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetAllFHIRSurveyAnswers(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetAllFHIRSurveyAnswers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAllFHIRSurveyAnswers(::grpc::ServerContext* /*context*/, const ::ondewo::survey::GetAllSurveyAnswersRequest* /*request*/, ::ondewo::survey::SurveyFHIRAnswersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAllFHIRSurveyAnswers(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateFHIRSurvey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateFHIRSurvey() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ondewo::survey::CreateFHIRSurveyRequest, ::ondewo::survey::Survey>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ondewo::survey::CreateFHIRSurveyRequest, ::ondewo::survey::Survey>* streamer) {
                       return this->StreamedCreateFHIRSurvey(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateFHIRSurvey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateFHIRSurvey(::grpc::ServerContext* /*context*/, const ::ondewo::survey::CreateFHIRSurveyRequest* /*request*/, ::ondewo::survey::Survey* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateFHIRSurvey(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ondewo::survey::CreateFHIRSurveyRequest,::ondewo::survey::Survey>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetFHIRSurveyAnswers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetFHIRSurveyAnswers() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ondewo::survey::GetSurveyAnswersRequest, ::ondewo::survey::SurveyFHIRAnswersResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ondewo::survey::GetSurveyAnswersRequest, ::ondewo::survey::SurveyFHIRAnswersResponse>* streamer) {
                       return this->StreamedGetFHIRSurveyAnswers(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetFHIRSurveyAnswers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetFHIRSurveyAnswers(::grpc::ServerContext* /*context*/, const ::ondewo::survey::GetSurveyAnswersRequest* /*request*/, ::ondewo::survey::SurveyFHIRAnswersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetFHIRSurveyAnswers(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ondewo::survey::GetSurveyAnswersRequest,::ondewo::survey::SurveyFHIRAnswersResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetAllFHIRSurveyAnswers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetAllFHIRSurveyAnswers() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ondewo::survey::GetAllSurveyAnswersRequest, ::ondewo::survey::SurveyFHIRAnswersResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ondewo::survey::GetAllSurveyAnswersRequest, ::ondewo::survey::SurveyFHIRAnswersResponse>* streamer) {
                       return this->StreamedGetAllFHIRSurveyAnswers(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetAllFHIRSurveyAnswers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetAllFHIRSurveyAnswers(::grpc::ServerContext* /*context*/, const ::ondewo::survey::GetAllSurveyAnswersRequest* /*request*/, ::ondewo::survey::SurveyFHIRAnswersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetAllFHIRSurveyAnswers(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ondewo::survey::GetAllSurveyAnswersRequest,::ondewo::survey::SurveyFHIRAnswersResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CreateFHIRSurvey<WithStreamedUnaryMethod_GetFHIRSurveyAnswers<WithStreamedUnaryMethod_GetAllFHIRSurveyAnswers<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CreateFHIRSurvey<WithStreamedUnaryMethod_GetFHIRSurveyAnswers<WithStreamedUnaryMethod_GetAllFHIRSurveyAnswers<Service > > > StreamedService;
};

}  // namespace survey
}  // namespace ondewo


#endif  // GRPC_ondewo_2fsurvey_2ffhir_2eproto__INCLUDED
