// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ondewo/survey/fhir.proto

#include "ondewo/survey/fhir.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ondewo {
namespace survey {
PROTOBUF_CONSTEXPR CreateFHIRSurveyRequest::CreateFHIRSurveyRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.fhir_questionnaire_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CreateFHIRSurveyRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CreateFHIRSurveyRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CreateFHIRSurveyRequestDefaultTypeInternal() {}
  union {
    CreateFHIRSurveyRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CreateFHIRSurveyRequestDefaultTypeInternal _CreateFHIRSurveyRequest_default_instance_;
PROTOBUF_CONSTEXPR SurveyFHIRAnswersResponse::SurveyFHIRAnswersResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.fhir_questionnaire_responses_)*/{}
  , /*decltype(_impl_.survey_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SurveyFHIRAnswersResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SurveyFHIRAnswersResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SurveyFHIRAnswersResponseDefaultTypeInternal() {}
  union {
    SurveyFHIRAnswersResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SurveyFHIRAnswersResponseDefaultTypeInternal _SurveyFHIRAnswersResponse_default_instance_;
}  // namespace survey
}  // namespace ondewo
static ::_pb::Metadata file_level_metadata_ondewo_2fsurvey_2ffhir_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_ondewo_2fsurvey_2ffhir_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ondewo_2fsurvey_2ffhir_2eproto = nullptr;

const uint32_t TableStruct_ondewo_2fsurvey_2ffhir_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ondewo::survey::CreateFHIRSurveyRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ondewo::survey::CreateFHIRSurveyRequest, _impl_.fhir_questionnaire_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ondewo::survey::SurveyFHIRAnswersResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ondewo::survey::SurveyFHIRAnswersResponse, _impl_.survey_id_),
  PROTOBUF_FIELD_OFFSET(::ondewo::survey::SurveyFHIRAnswersResponse, _impl_.fhir_questionnaire_responses_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ondewo::survey::CreateFHIRSurveyRequest)},
  { 7, -1, -1, sizeof(::ondewo::survey::SurveyFHIRAnswersResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ondewo::survey::_CreateFHIRSurveyRequest_default_instance_._instance,
  &::ondewo::survey::_SurveyFHIRAnswersResponse_default_instance_._instance,
};

const char descriptor_table_protodef_ondewo_2fsurvey_2ffhir_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030ondewo/survey/fhir.proto\022\rondewo.surve"
  "y\032\034google/api/annotations.proto\032\032ondewo/"
  "survey/survey.proto\032\034google/protobuf/str"
  "uct.proto\"N\n\027CreateFHIRSurveyRequest\0223\n\022"
  "fhir_questionnaire\030\001 \001(\0132\027.google.protob"
  "uf.Struct\"m\n\031SurveyFHIRAnswersResponse\022\021"
  "\n\tsurvey_id\030\001 \001(\t\022=\n\034fhir_questionnaire_"
  "responses\030\002 \003(\0132\027.google.protobuf.Struct"
  "2\265\003\n\004FHIR\022j\n\020CreateFHIRSurvey\022&.ondewo.s"
  "urvey.CreateFHIRSurveyRequest\032\025.ondewo.s"
  "urvey.Survey\"\027\202\323\344\223\002\021\"\014/fhir_survey:\001*\022\243\001"
  "\n\024GetFHIRSurveyAnswers\022&.ondewo.survey.G"
  "etSurveyAnswersRequest\032(.ondewo.survey.S"
  "urveyFHIRAnswersResponse\"9\202\323\344\223\0023\0221/surve"
  "y/{survey_id=*}/fhir_answers/{session_id"
  "=*}\022\232\001\n\027GetAllFHIRSurveyAnswers\022).ondewo"
  ".survey.GetAllSurveyAnswersRequest\032(.ond"
  "ewo.survey.SurveyFHIRAnswersResponse\"*\202\323"
  "\344\223\002$\022\"/survey/{survey_id=*}/fhir_answers"
  "b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_ondewo_2fsurvey_2ffhir_2eproto_deps[3] = {
  &::descriptor_table_google_2fapi_2fannotations_2eproto,
  &::descriptor_table_google_2fprotobuf_2fstruct_2eproto,
  &::descriptor_table_ondewo_2fsurvey_2fsurvey_2eproto,
};
static ::_pbi::once_flag descriptor_table_ondewo_2fsurvey_2ffhir_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ondewo_2fsurvey_2ffhir_2eproto = {
    false, false, 768, descriptor_table_protodef_ondewo_2fsurvey_2ffhir_2eproto,
    "ondewo/survey/fhir.proto",
    &descriptor_table_ondewo_2fsurvey_2ffhir_2eproto_once, descriptor_table_ondewo_2fsurvey_2ffhir_2eproto_deps, 3, 2,
    schemas, file_default_instances, TableStruct_ondewo_2fsurvey_2ffhir_2eproto::offsets,
    file_level_metadata_ondewo_2fsurvey_2ffhir_2eproto, file_level_enum_descriptors_ondewo_2fsurvey_2ffhir_2eproto,
    file_level_service_descriptors_ondewo_2fsurvey_2ffhir_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ondewo_2fsurvey_2ffhir_2eproto_getter() {
  return &descriptor_table_ondewo_2fsurvey_2ffhir_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ondewo_2fsurvey_2ffhir_2eproto(&descriptor_table_ondewo_2fsurvey_2ffhir_2eproto);
namespace ondewo {
namespace survey {

// ===================================================================

class CreateFHIRSurveyRequest::_Internal {
 public:
  static const ::PROTOBUF_NAMESPACE_ID::Struct& fhir_questionnaire(const CreateFHIRSurveyRequest* msg);
};

const ::PROTOBUF_NAMESPACE_ID::Struct&
CreateFHIRSurveyRequest::_Internal::fhir_questionnaire(const CreateFHIRSurveyRequest* msg) {
  return *msg->_impl_.fhir_questionnaire_;
}
void CreateFHIRSurveyRequest::clear_fhir_questionnaire() {
  if (GetArenaForAllocation() == nullptr && _impl_.fhir_questionnaire_ != nullptr) {
    delete _impl_.fhir_questionnaire_;
  }
  _impl_.fhir_questionnaire_ = nullptr;
}
CreateFHIRSurveyRequest::CreateFHIRSurveyRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ondewo.survey.CreateFHIRSurveyRequest)
}
CreateFHIRSurveyRequest::CreateFHIRSurveyRequest(const CreateFHIRSurveyRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CreateFHIRSurveyRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.fhir_questionnaire_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_fhir_questionnaire()) {
    _this->_impl_.fhir_questionnaire_ = new ::PROTOBUF_NAMESPACE_ID::Struct(*from._impl_.fhir_questionnaire_);
  }
  // @@protoc_insertion_point(copy_constructor:ondewo.survey.CreateFHIRSurveyRequest)
}

inline void CreateFHIRSurveyRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.fhir_questionnaire_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CreateFHIRSurveyRequest::~CreateFHIRSurveyRequest() {
  // @@protoc_insertion_point(destructor:ondewo.survey.CreateFHIRSurveyRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CreateFHIRSurveyRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.fhir_questionnaire_;
}

void CreateFHIRSurveyRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CreateFHIRSurveyRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ondewo.survey.CreateFHIRSurveyRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.fhir_questionnaire_ != nullptr) {
    delete _impl_.fhir_questionnaire_;
  }
  _impl_.fhir_questionnaire_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CreateFHIRSurveyRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .google.protobuf.Struct fhir_questionnaire = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_fhir_questionnaire(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CreateFHIRSurveyRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ondewo.survey.CreateFHIRSurveyRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.Struct fhir_questionnaire = 1;
  if (this->_internal_has_fhir_questionnaire()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::fhir_questionnaire(this),
        _Internal::fhir_questionnaire(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ondewo.survey.CreateFHIRSurveyRequest)
  return target;
}

size_t CreateFHIRSurveyRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ondewo.survey.CreateFHIRSurveyRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .google.protobuf.Struct fhir_questionnaire = 1;
  if (this->_internal_has_fhir_questionnaire()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.fhir_questionnaire_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CreateFHIRSurveyRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CreateFHIRSurveyRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CreateFHIRSurveyRequest::GetClassData() const { return &_class_data_; }


void CreateFHIRSurveyRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CreateFHIRSurveyRequest*>(&to_msg);
  auto& from = static_cast<const CreateFHIRSurveyRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ondewo.survey.CreateFHIRSurveyRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_fhir_questionnaire()) {
    _this->_internal_mutable_fhir_questionnaire()->::PROTOBUF_NAMESPACE_ID::Struct::MergeFrom(
        from._internal_fhir_questionnaire());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CreateFHIRSurveyRequest::CopyFrom(const CreateFHIRSurveyRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ondewo.survey.CreateFHIRSurveyRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateFHIRSurveyRequest::IsInitialized() const {
  return true;
}

void CreateFHIRSurveyRequest::InternalSwap(CreateFHIRSurveyRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.fhir_questionnaire_, other->_impl_.fhir_questionnaire_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CreateFHIRSurveyRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ondewo_2fsurvey_2ffhir_2eproto_getter, &descriptor_table_ondewo_2fsurvey_2ffhir_2eproto_once,
      file_level_metadata_ondewo_2fsurvey_2ffhir_2eproto[0]);
}

// ===================================================================

class SurveyFHIRAnswersResponse::_Internal {
 public:
};

void SurveyFHIRAnswersResponse::clear_fhir_questionnaire_responses() {
  _impl_.fhir_questionnaire_responses_.Clear();
}
SurveyFHIRAnswersResponse::SurveyFHIRAnswersResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ondewo.survey.SurveyFHIRAnswersResponse)
}
SurveyFHIRAnswersResponse::SurveyFHIRAnswersResponse(const SurveyFHIRAnswersResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SurveyFHIRAnswersResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.fhir_questionnaire_responses_){from._impl_.fhir_questionnaire_responses_}
    , decltype(_impl_.survey_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.survey_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.survey_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_survey_id().empty()) {
    _this->_impl_.survey_id_.Set(from._internal_survey_id(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ondewo.survey.SurveyFHIRAnswersResponse)
}

inline void SurveyFHIRAnswersResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.fhir_questionnaire_responses_){arena}
    , decltype(_impl_.survey_id_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.survey_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.survey_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SurveyFHIRAnswersResponse::~SurveyFHIRAnswersResponse() {
  // @@protoc_insertion_point(destructor:ondewo.survey.SurveyFHIRAnswersResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SurveyFHIRAnswersResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.fhir_questionnaire_responses_.~RepeatedPtrField();
  _impl_.survey_id_.Destroy();
}

void SurveyFHIRAnswersResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SurveyFHIRAnswersResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ondewo.survey.SurveyFHIRAnswersResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.fhir_questionnaire_responses_.Clear();
  _impl_.survey_id_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SurveyFHIRAnswersResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string survey_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_survey_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ondewo.survey.SurveyFHIRAnswersResponse.survey_id"));
        } else
          goto handle_unusual;
        continue;
      // repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_fhir_questionnaire_responses(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SurveyFHIRAnswersResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ondewo.survey.SurveyFHIRAnswersResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string survey_id = 1;
  if (!this->_internal_survey_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_survey_id().data(), static_cast<int>(this->_internal_survey_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ondewo.survey.SurveyFHIRAnswersResponse.survey_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_survey_id(), target);
  }

  // repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_fhir_questionnaire_responses_size()); i < n; i++) {
    const auto& repfield = this->_internal_fhir_questionnaire_responses(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ondewo.survey.SurveyFHIRAnswersResponse)
  return target;
}

size_t SurveyFHIRAnswersResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ondewo.survey.SurveyFHIRAnswersResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .google.protobuf.Struct fhir_questionnaire_responses = 2;
  total_size += 1UL * this->_internal_fhir_questionnaire_responses_size();
  for (const auto& msg : this->_impl_.fhir_questionnaire_responses_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string survey_id = 1;
  if (!this->_internal_survey_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_survey_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SurveyFHIRAnswersResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SurveyFHIRAnswersResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SurveyFHIRAnswersResponse::GetClassData() const { return &_class_data_; }


void SurveyFHIRAnswersResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SurveyFHIRAnswersResponse*>(&to_msg);
  auto& from = static_cast<const SurveyFHIRAnswersResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ondewo.survey.SurveyFHIRAnswersResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.fhir_questionnaire_responses_.MergeFrom(from._impl_.fhir_questionnaire_responses_);
  if (!from._internal_survey_id().empty()) {
    _this->_internal_set_survey_id(from._internal_survey_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SurveyFHIRAnswersResponse::CopyFrom(const SurveyFHIRAnswersResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ondewo.survey.SurveyFHIRAnswersResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SurveyFHIRAnswersResponse::IsInitialized() const {
  return true;
}

void SurveyFHIRAnswersResponse::InternalSwap(SurveyFHIRAnswersResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.fhir_questionnaire_responses_.InternalSwap(&other->_impl_.fhir_questionnaire_responses_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.survey_id_, lhs_arena,
      &other->_impl_.survey_id_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata SurveyFHIRAnswersResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ondewo_2fsurvey_2ffhir_2eproto_getter, &descriptor_table_ondewo_2fsurvey_2ffhir_2eproto_once,
      file_level_metadata_ondewo_2fsurvey_2ffhir_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace survey
}  // namespace ondewo
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ondewo::survey::CreateFHIRSurveyRequest*
Arena::CreateMaybeMessage< ::ondewo::survey::CreateFHIRSurveyRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ondewo::survey::CreateFHIRSurveyRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::ondewo::survey::SurveyFHIRAnswersResponse*
Arena::CreateMaybeMessage< ::ondewo::survey::SurveyFHIRAnswersResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ondewo::survey::SurveyFHIRAnswersResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
