// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ondewo/survey/fhir.proto

#include "ondewo/survey/fhir.pb.h"
#include "ondewo/survey/fhir.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ondewo {
namespace survey {

static const char* FHIR_method_names[] = {
  "/ondewo.survey.FHIR/CreateFHIRSurvey",
  "/ondewo.survey.FHIR/GetFHIRSurveyAnswers",
  "/ondewo.survey.FHIR/GetAllFHIRSurveyAnswers",
};

std::unique_ptr< FHIR::Stub> FHIR::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FHIR::Stub> stub(new FHIR::Stub(channel, options));
  return stub;
}

FHIR::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateFHIRSurvey_(FHIR_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetFHIRSurveyAnswers_(FHIR_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetAllFHIRSurveyAnswers_(FHIR_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FHIR::Stub::CreateFHIRSurvey(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest& request, ::ondewo::survey::Survey* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::survey::CreateFHIRSurveyRequest, ::ondewo::survey::Survey, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateFHIRSurvey_, context, request, response);
}

void FHIR::Stub::async::CreateFHIRSurvey(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest* request, ::ondewo::survey::Survey* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::survey::CreateFHIRSurveyRequest, ::ondewo::survey::Survey, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateFHIRSurvey_, context, request, response, std::move(f));
}

void FHIR::Stub::async::CreateFHIRSurvey(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest* request, ::ondewo::survey::Survey* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateFHIRSurvey_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::Survey>* FHIR::Stub::PrepareAsyncCreateFHIRSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::survey::Survey, ::ondewo::survey::CreateFHIRSurveyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateFHIRSurvey_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::Survey>* FHIR::Stub::AsyncCreateFHIRSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateFHIRSurveyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FHIR::Stub::GetFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest& request, ::ondewo::survey::SurveyFHIRAnswersResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::survey::GetSurveyAnswersRequest, ::ondewo::survey::SurveyFHIRAnswersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetFHIRSurveyAnswers_, context, request, response);
}

void FHIR::Stub::async::GetFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::survey::GetSurveyAnswersRequest, ::ondewo::survey::SurveyFHIRAnswersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFHIRSurveyAnswers_, context, request, response, std::move(f));
}

void FHIR::Stub::async::GetFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFHIRSurveyAnswers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyFHIRAnswersResponse>* FHIR::Stub::PrepareAsyncGetFHIRSurveyAnswersRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::survey::SurveyFHIRAnswersResponse, ::ondewo::survey::GetSurveyAnswersRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetFHIRSurveyAnswers_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyFHIRAnswersResponse>* FHIR::Stub::AsyncGetFHIRSurveyAnswersRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetFHIRSurveyAnswersRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FHIR::Stub::GetAllFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest& request, ::ondewo::survey::SurveyFHIRAnswersResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::survey::GetAllSurveyAnswersRequest, ::ondewo::survey::SurveyFHIRAnswersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAllFHIRSurveyAnswers_, context, request, response);
}

void FHIR::Stub::async::GetAllFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::survey::GetAllSurveyAnswersRequest, ::ondewo::survey::SurveyFHIRAnswersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllFHIRSurveyAnswers_, context, request, response, std::move(f));
}

void FHIR::Stub::async::GetAllFHIRSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllFHIRSurveyAnswers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyFHIRAnswersResponse>* FHIR::Stub::PrepareAsyncGetAllFHIRSurveyAnswersRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::survey::SurveyFHIRAnswersResponse, ::ondewo::survey::GetAllSurveyAnswersRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAllFHIRSurveyAnswers_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyFHIRAnswersResponse>* FHIR::Stub::AsyncGetAllFHIRSurveyAnswersRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAllFHIRSurveyAnswersRaw(context, request, cq);
  result->StartCall();
  return result;
}

FHIR::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FHIR_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FHIR::Service, ::ondewo::survey::CreateFHIRSurveyRequest, ::ondewo::survey::Survey, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FHIR::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::survey::CreateFHIRSurveyRequest* req,
             ::ondewo::survey::Survey* resp) {
               return service->CreateFHIRSurvey(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FHIR_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FHIR::Service, ::ondewo::survey::GetSurveyAnswersRequest, ::ondewo::survey::SurveyFHIRAnswersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FHIR::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::survey::GetSurveyAnswersRequest* req,
             ::ondewo::survey::SurveyFHIRAnswersResponse* resp) {
               return service->GetFHIRSurveyAnswers(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FHIR_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FHIR::Service, ::ondewo::survey::GetAllSurveyAnswersRequest, ::ondewo::survey::SurveyFHIRAnswersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FHIR::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::survey::GetAllSurveyAnswersRequest* req,
             ::ondewo::survey::SurveyFHIRAnswersResponse* resp) {
               return service->GetAllFHIRSurveyAnswers(ctx, req, resp);
             }, this)));
}

FHIR::Service::~Service() {
}

::grpc::Status FHIR::Service::CreateFHIRSurvey(::grpc::ServerContext* context, const ::ondewo::survey::CreateFHIRSurveyRequest* request, ::ondewo::survey::Survey* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FHIR::Service::GetFHIRSurveyAnswers(::grpc::ServerContext* context, const ::ondewo::survey::GetSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FHIR::Service::GetAllFHIRSurveyAnswers(::grpc::ServerContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest* request, ::ondewo::survey::SurveyFHIRAnswersResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ondewo
}  // namespace survey

