// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ondewo/survey/survey.proto

#include "ondewo/survey/survey.pb.h"
#include "ondewo/survey/survey.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ondewo {
namespace survey {

static const char* Surveys_method_names[] = {
  "/ondewo.survey.Surveys/CreateSurvey",
  "/ondewo.survey.Surveys/GetSurvey",
  "/ondewo.survey.Surveys/UpdateSurvey",
  "/ondewo.survey.Surveys/DeleteSurvey",
  "/ondewo.survey.Surveys/ListSurveys",
  "/ondewo.survey.Surveys/GetSurveyAnswers",
  "/ondewo.survey.Surveys/GetAllSurveyAnswers",
  "/ondewo.survey.Surveys/CreateAgentSurvey",
  "/ondewo.survey.Surveys/UpdateAgentSurvey",
  "/ondewo.survey.Surveys/DeleteAgentSurvey",
};

std::unique_ptr< Surveys::Stub> Surveys::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Surveys::Stub> stub(new Surveys::Stub(channel, options));
  return stub;
}

Surveys::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateSurvey_(Surveys_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSurvey_(Surveys_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateSurvey_(Surveys_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteSurvey_(Surveys_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListSurveys_(Surveys_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSurveyAnswers_(Surveys_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetAllSurveyAnswers_(Surveys_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateAgentSurvey_(Surveys_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateAgentSurvey_(Surveys_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteAgentSurvey_(Surveys_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Surveys::Stub::CreateSurvey(::grpc::ClientContext* context, const ::ondewo::survey::CreateSurveyRequest& request, ::ondewo::survey::Survey* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::survey::CreateSurveyRequest, ::ondewo::survey::Survey, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateSurvey_, context, request, response);
}

void Surveys::Stub::async::CreateSurvey(::grpc::ClientContext* context, const ::ondewo::survey::CreateSurveyRequest* request, ::ondewo::survey::Survey* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::survey::CreateSurveyRequest, ::ondewo::survey::Survey, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateSurvey_, context, request, response, std::move(f));
}

void Surveys::Stub::async::CreateSurvey(::grpc::ClientContext* context, const ::ondewo::survey::CreateSurveyRequest* request, ::ondewo::survey::Survey* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateSurvey_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::Survey>* Surveys::Stub::PrepareAsyncCreateSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::CreateSurveyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::survey::Survey, ::ondewo::survey::CreateSurveyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateSurvey_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::Survey>* Surveys::Stub::AsyncCreateSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::CreateSurveyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateSurveyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Surveys::Stub::GetSurvey(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyRequest& request, ::ondewo::survey::Survey* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::survey::GetSurveyRequest, ::ondewo::survey::Survey, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSurvey_, context, request, response);
}

void Surveys::Stub::async::GetSurvey(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyRequest* request, ::ondewo::survey::Survey* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::survey::GetSurveyRequest, ::ondewo::survey::Survey, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSurvey_, context, request, response, std::move(f));
}

void Surveys::Stub::async::GetSurvey(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyRequest* request, ::ondewo::survey::Survey* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSurvey_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::Survey>* Surveys::Stub::PrepareAsyncGetSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::survey::Survey, ::ondewo::survey::GetSurveyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSurvey_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::Survey>* Surveys::Stub::AsyncGetSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSurveyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Surveys::Stub::UpdateSurvey(::grpc::ClientContext* context, const ::ondewo::survey::UpdateSurveyRequest& request, ::ondewo::survey::Survey* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::survey::UpdateSurveyRequest, ::ondewo::survey::Survey, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateSurvey_, context, request, response);
}

void Surveys::Stub::async::UpdateSurvey(::grpc::ClientContext* context, const ::ondewo::survey::UpdateSurveyRequest* request, ::ondewo::survey::Survey* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::survey::UpdateSurveyRequest, ::ondewo::survey::Survey, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateSurvey_, context, request, response, std::move(f));
}

void Surveys::Stub::async::UpdateSurvey(::grpc::ClientContext* context, const ::ondewo::survey::UpdateSurveyRequest* request, ::ondewo::survey::Survey* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateSurvey_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::Survey>* Surveys::Stub::PrepareAsyncUpdateSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::UpdateSurveyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::survey::Survey, ::ondewo::survey::UpdateSurveyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateSurvey_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::Survey>* Surveys::Stub::AsyncUpdateSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::UpdateSurveyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateSurveyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Surveys::Stub::DeleteSurvey(::grpc::ClientContext* context, const ::ondewo::survey::DeleteSurveyRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::survey::DeleteSurveyRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteSurvey_, context, request, response);
}

void Surveys::Stub::async::DeleteSurvey(::grpc::ClientContext* context, const ::ondewo::survey::DeleteSurveyRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::survey::DeleteSurveyRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteSurvey_, context, request, response, std::move(f));
}

void Surveys::Stub::async::DeleteSurvey(::grpc::ClientContext* context, const ::ondewo::survey::DeleteSurveyRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteSurvey_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Surveys::Stub::PrepareAsyncDeleteSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::DeleteSurveyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::ondewo::survey::DeleteSurveyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteSurvey_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Surveys::Stub::AsyncDeleteSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::DeleteSurveyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteSurveyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Surveys::Stub::ListSurveys(::grpc::ClientContext* context, const ::ondewo::survey::ListSurveysRequest& request, ::ondewo::survey::ListSurveysResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::survey::ListSurveysRequest, ::ondewo::survey::ListSurveysResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListSurveys_, context, request, response);
}

void Surveys::Stub::async::ListSurveys(::grpc::ClientContext* context, const ::ondewo::survey::ListSurveysRequest* request, ::ondewo::survey::ListSurveysResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::survey::ListSurveysRequest, ::ondewo::survey::ListSurveysResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListSurveys_, context, request, response, std::move(f));
}

void Surveys::Stub::async::ListSurveys(::grpc::ClientContext* context, const ::ondewo::survey::ListSurveysRequest* request, ::ondewo::survey::ListSurveysResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListSurveys_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::ListSurveysResponse>* Surveys::Stub::PrepareAsyncListSurveysRaw(::grpc::ClientContext* context, const ::ondewo::survey::ListSurveysRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::survey::ListSurveysResponse, ::ondewo::survey::ListSurveysRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListSurveys_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::ListSurveysResponse>* Surveys::Stub::AsyncListSurveysRaw(::grpc::ClientContext* context, const ::ondewo::survey::ListSurveysRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListSurveysRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Surveys::Stub::GetSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest& request, ::ondewo::survey::SurveyAnswersResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::survey::GetSurveyAnswersRequest, ::ondewo::survey::SurveyAnswersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSurveyAnswers_, context, request, response);
}

void Surveys::Stub::async::GetSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest* request, ::ondewo::survey::SurveyAnswersResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::survey::GetSurveyAnswersRequest, ::ondewo::survey::SurveyAnswersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSurveyAnswers_, context, request, response, std::move(f));
}

void Surveys::Stub::async::GetSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest* request, ::ondewo::survey::SurveyAnswersResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSurveyAnswers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyAnswersResponse>* Surveys::Stub::PrepareAsyncGetSurveyAnswersRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::survey::SurveyAnswersResponse, ::ondewo::survey::GetSurveyAnswersRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSurveyAnswers_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyAnswersResponse>* Surveys::Stub::AsyncGetSurveyAnswersRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSurveyAnswersRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Surveys::Stub::GetAllSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest& request, ::ondewo::survey::SurveyAnswersResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::survey::GetAllSurveyAnswersRequest, ::ondewo::survey::SurveyAnswersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAllSurveyAnswers_, context, request, response);
}

void Surveys::Stub::async::GetAllSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest* request, ::ondewo::survey::SurveyAnswersResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::survey::GetAllSurveyAnswersRequest, ::ondewo::survey::SurveyAnswersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllSurveyAnswers_, context, request, response, std::move(f));
}

void Surveys::Stub::async::GetAllSurveyAnswers(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest* request, ::ondewo::survey::SurveyAnswersResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllSurveyAnswers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyAnswersResponse>* Surveys::Stub::PrepareAsyncGetAllSurveyAnswersRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::survey::SurveyAnswersResponse, ::ondewo::survey::GetAllSurveyAnswersRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAllSurveyAnswers_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::SurveyAnswersResponse>* Surveys::Stub::AsyncGetAllSurveyAnswersRaw(::grpc::ClientContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAllSurveyAnswersRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Surveys::Stub::CreateAgentSurvey(::grpc::ClientContext* context, const ::ondewo::survey::AgentSurveyRequest& request, ::ondewo::survey::AgentSurveyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::survey::AgentSurveyRequest, ::ondewo::survey::AgentSurveyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateAgentSurvey_, context, request, response);
}

void Surveys::Stub::async::CreateAgentSurvey(::grpc::ClientContext* context, const ::ondewo::survey::AgentSurveyRequest* request, ::ondewo::survey::AgentSurveyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::survey::AgentSurveyRequest, ::ondewo::survey::AgentSurveyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateAgentSurvey_, context, request, response, std::move(f));
}

void Surveys::Stub::async::CreateAgentSurvey(::grpc::ClientContext* context, const ::ondewo::survey::AgentSurveyRequest* request, ::ondewo::survey::AgentSurveyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateAgentSurvey_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::AgentSurveyResponse>* Surveys::Stub::PrepareAsyncCreateAgentSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::AgentSurveyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::survey::AgentSurveyResponse, ::ondewo::survey::AgentSurveyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateAgentSurvey_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::AgentSurveyResponse>* Surveys::Stub::AsyncCreateAgentSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::AgentSurveyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateAgentSurveyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Surveys::Stub::UpdateAgentSurvey(::grpc::ClientContext* context, const ::ondewo::survey::AgentSurveyRequest& request, ::ondewo::survey::AgentSurveyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::survey::AgentSurveyRequest, ::ondewo::survey::AgentSurveyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateAgentSurvey_, context, request, response);
}

void Surveys::Stub::async::UpdateAgentSurvey(::grpc::ClientContext* context, const ::ondewo::survey::AgentSurveyRequest* request, ::ondewo::survey::AgentSurveyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::survey::AgentSurveyRequest, ::ondewo::survey::AgentSurveyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateAgentSurvey_, context, request, response, std::move(f));
}

void Surveys::Stub::async::UpdateAgentSurvey(::grpc::ClientContext* context, const ::ondewo::survey::AgentSurveyRequest* request, ::ondewo::survey::AgentSurveyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateAgentSurvey_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::AgentSurveyResponse>* Surveys::Stub::PrepareAsyncUpdateAgentSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::AgentSurveyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::survey::AgentSurveyResponse, ::ondewo::survey::AgentSurveyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateAgentSurvey_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::survey::AgentSurveyResponse>* Surveys::Stub::AsyncUpdateAgentSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::AgentSurveyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateAgentSurveyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Surveys::Stub::DeleteAgentSurvey(::grpc::ClientContext* context, const ::ondewo::survey::AgentSurveyRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::survey::AgentSurveyRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteAgentSurvey_, context, request, response);
}

void Surveys::Stub::async::DeleteAgentSurvey(::grpc::ClientContext* context, const ::ondewo::survey::AgentSurveyRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::survey::AgentSurveyRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteAgentSurvey_, context, request, response, std::move(f));
}

void Surveys::Stub::async::DeleteAgentSurvey(::grpc::ClientContext* context, const ::ondewo::survey::AgentSurveyRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteAgentSurvey_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Surveys::Stub::PrepareAsyncDeleteAgentSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::AgentSurveyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::ondewo::survey::AgentSurveyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteAgentSurvey_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Surveys::Stub::AsyncDeleteAgentSurveyRaw(::grpc::ClientContext* context, const ::ondewo::survey::AgentSurveyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteAgentSurveyRaw(context, request, cq);
  result->StartCall();
  return result;
}

Surveys::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Surveys_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Surveys::Service, ::ondewo::survey::CreateSurveyRequest, ::ondewo::survey::Survey, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Surveys::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::survey::CreateSurveyRequest* req,
             ::ondewo::survey::Survey* resp) {
               return service->CreateSurvey(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Surveys_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Surveys::Service, ::ondewo::survey::GetSurveyRequest, ::ondewo::survey::Survey, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Surveys::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::survey::GetSurveyRequest* req,
             ::ondewo::survey::Survey* resp) {
               return service->GetSurvey(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Surveys_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Surveys::Service, ::ondewo::survey::UpdateSurveyRequest, ::ondewo::survey::Survey, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Surveys::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::survey::UpdateSurveyRequest* req,
             ::ondewo::survey::Survey* resp) {
               return service->UpdateSurvey(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Surveys_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Surveys::Service, ::ondewo::survey::DeleteSurveyRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Surveys::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::survey::DeleteSurveyRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->DeleteSurvey(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Surveys_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Surveys::Service, ::ondewo::survey::ListSurveysRequest, ::ondewo::survey::ListSurveysResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Surveys::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::survey::ListSurveysRequest* req,
             ::ondewo::survey::ListSurveysResponse* resp) {
               return service->ListSurveys(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Surveys_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Surveys::Service, ::ondewo::survey::GetSurveyAnswersRequest, ::ondewo::survey::SurveyAnswersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Surveys::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::survey::GetSurveyAnswersRequest* req,
             ::ondewo::survey::SurveyAnswersResponse* resp) {
               return service->GetSurveyAnswers(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Surveys_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Surveys::Service, ::ondewo::survey::GetAllSurveyAnswersRequest, ::ondewo::survey::SurveyAnswersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Surveys::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::survey::GetAllSurveyAnswersRequest* req,
             ::ondewo::survey::SurveyAnswersResponse* resp) {
               return service->GetAllSurveyAnswers(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Surveys_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Surveys::Service, ::ondewo::survey::AgentSurveyRequest, ::ondewo::survey::AgentSurveyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Surveys::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::survey::AgentSurveyRequest* req,
             ::ondewo::survey::AgentSurveyResponse* resp) {
               return service->CreateAgentSurvey(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Surveys_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Surveys::Service, ::ondewo::survey::AgentSurveyRequest, ::ondewo::survey::AgentSurveyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Surveys::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::survey::AgentSurveyRequest* req,
             ::ondewo::survey::AgentSurveyResponse* resp) {
               return service->UpdateAgentSurvey(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Surveys_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Surveys::Service, ::ondewo::survey::AgentSurveyRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Surveys::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::survey::AgentSurveyRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->DeleteAgentSurvey(ctx, req, resp);
             }, this)));
}

Surveys::Service::~Service() {
}

::grpc::Status Surveys::Service::CreateSurvey(::grpc::ServerContext* context, const ::ondewo::survey::CreateSurveyRequest* request, ::ondewo::survey::Survey* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Surveys::Service::GetSurvey(::grpc::ServerContext* context, const ::ondewo::survey::GetSurveyRequest* request, ::ondewo::survey::Survey* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Surveys::Service::UpdateSurvey(::grpc::ServerContext* context, const ::ondewo::survey::UpdateSurveyRequest* request, ::ondewo::survey::Survey* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Surveys::Service::DeleteSurvey(::grpc::ServerContext* context, const ::ondewo::survey::DeleteSurveyRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Surveys::Service::ListSurveys(::grpc::ServerContext* context, const ::ondewo::survey::ListSurveysRequest* request, ::ondewo::survey::ListSurveysResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Surveys::Service::GetSurveyAnswers(::grpc::ServerContext* context, const ::ondewo::survey::GetSurveyAnswersRequest* request, ::ondewo::survey::SurveyAnswersResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Surveys::Service::GetAllSurveyAnswers(::grpc::ServerContext* context, const ::ondewo::survey::GetAllSurveyAnswersRequest* request, ::ondewo::survey::SurveyAnswersResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Surveys::Service::CreateAgentSurvey(::grpc::ServerContext* context, const ::ondewo::survey::AgentSurveyRequest* request, ::ondewo::survey::AgentSurveyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Surveys::Service::UpdateAgentSurvey(::grpc::ServerContext* context, const ::ondewo::survey::AgentSurveyRequest* request, ::ondewo::survey::AgentSurveyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Surveys::Service::DeleteAgentSurvey(::grpc::ServerContext* context, const ::ondewo::survey::AgentSurveyRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ondewo
}  // namespace survey

